Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 118, in <module>
    run_parallel_permtests(output_basedir,n_workers)
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 103, in run_parallel_permtests
    agg_data,fpairnames = ld_pt.aggregate_cancorrs(dirlocs)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_permtest.py", line 75, in aggregate_cancorrs
    all_pair_data = np.concatenate(tuple(cancorrs),axis=1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 10 and the array at index 5 has size 9
