Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_perm.py", line 50, in <module>
    testval = ld_pt.ld_br.find_reg_val(reglist,namelist[0],namelist[1])
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_brainrep.py", line 168, in find_reg_val
    idx = reg_list[0].index(pairname)
ValueError: 'NM_PROFUMO_and_Maps_PROFUMO' is not in list
