Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/pull_cancorrs.py", line 43, in <module>
    pull_cancorrs(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4], ftype_par=sys.argv[5])
  File "/scratch/tyoeasley/brain_representations/src_py/pull_cancorrs.py", line 25, in pull_cancorrs
    with open(input_floc,'rb') as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/tyoeasley/brain_representations/nonPH_analysis/CCA/stability_testing/CCA_stbl_paragg_2022Jan02/NM_PROFUMO_and_Maps_PROFUMO.CCA_res'
