Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/pull_cancorrs.py", line 43, in <module>
    pull_cancorrs(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4], ftype_par=sys.argv[5])
IndexError: list index out of range
