/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/home/e.ty/.conda/envs/alg_top_neuro/lib/python3.7/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/pull_cancorrs.py", line 44, in <module>
    pull_cancorrs(sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4])
  File "/scratch/tyoeasley/brain_representations/src_py/pull_cancorrs.py", line 35, in pull_cancorrs
    write.writerow(cancorrs)
_csv.Error: iterable expected, not numpy.float64
