Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_dimstab.py", line 119, in <module>
    main(sys.argv)
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_dimstab.py", line 75, in main
    run_dimensional_stability_tst(reps,output_basedir,permset,namelist,regval_list,decomp_method,n_workers)
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_dimstab.py", line 107, in run_dimensional_stability_tst
    pull_cancorrs.pull_res_cancorrs(data_outdir)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/pull_cancorrs.py", line 61, in pull_res_cancorrs
    with open(varout_locs[i],'w') as fout:
NameError: name 'i' is not defined
