/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_stability.py:217: RuntimeWarning: invalid value encountered in log
  cancorr_max = [None]*n_iter
Traceback (most recent call last):
  File "/scratch/tyoeasley/brain_representations/src_py/run_lindecomp_stbl.py", line 4, in <module>
    ld_st.stability_testing(sys.argv[1],sys.argv[2],listpath=sys.argv[3],decomp_method=sys.argv[4])
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_stability.py", line 65, in stability_testing
    stability_summary = summarizer(decomp_vals)
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_stability.py", line 143, in summ_CCA
    for i in range(n_pairs):
  File "/mnt/beegfs/scratch/tyoeasley/brain_representations/src_py/lindecomp_stability.py", line 126, in __init__
    self.comp_dists_spectral = comp_dists_spectral
NameError: name 'corr_sumaries' is not defined
